# Generated by Django 3.2.4 on 2021-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotteryGameName', models.CharField(max_length=255)),
                ('drawFlowFund', models.CharField(max_length=255)),
                ('drawFlowFundRj', models.CharField(max_length=255)),
                ('estimateDrawTime', models.DateTimeField()),
                ('isGetKjpdf', models.IntegerField()),
                ('isGetXlpdf', models.IntegerField()),
                ('lotteryDrawNum', models.CharField(max_length=255)),
                ('lotteryDrawResult', models.CharField(max_length=255)),
                ('lotteryDrawStatus', models.IntegerField()),
                ('lotteryDrawTime', models.DateTimeField()),
                ('lotteryEquipmentCount', models.IntegerField()),
                ('lotteryGameNum', models.CharField(max_length=255)),
                ('lotteryGamePronum', models.IntegerField()),
                ('lotteryPaidBeginTime', models.DateTimeField()),
                ('lotteryPaidEndTime', models.DateTimeField()),
                ('lotteryPromotionFlag', models.IntegerField()),
                ('lotterySaleBeginTime', models.DateTimeField()),
                ('lotterySaleEndTimeUnix', models.IntegerField()),
                ('lotterySaleEndtime', models.DateTimeField()),
                ('lotterySuspendedFlag', models.IntegerField()),
                ('lotteryUnsortDrawresult', models.CharField(max_length=255)),
                ('matchList', models.JSONField()),
                ('pdfType', models.IntegerField()),
                ('poolBalanceAfterdraw', models.CharField(max_length=255)),
                ('poolBalanceAfterdrawRj', models.CharField(max_length=255)),
                ('prizeLevelList', models.JSONField()),
                ('prizeLevelListRj', models.JSONField()),
                ('ruleType', models.IntegerField()),
                ('termList', models.JSONField()),
                ('totalSaleAmount', models.CharField(max_length=255)),
                ('totalSaleAmountRj', models.CharField(max_length=255)),
                ('verify', models.IntegerField()),
                ('vtoolsConfig', models.JSONField()),
            ],
            options={
                'verbose_name': '开奖历史数据',
                'verbose_name_plural': '开奖历史数据',
            },
        ),
    ]
