# Generated by Django 3.2.4 on 2021-07-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_lottery_estimatedrawtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='lotteryDrawTime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lotteryPaidBeginTime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lotteryPaidEndTime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lotterySaleBeginTime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lotterySaleEndtime',
            field=models.CharField(max_length=255),
        ),
    ]
