version: "3"
services:
  django:
    build: .
    container_name: django
    #    command: python /djangocode/manage.py runserver 0.0.0.0:8000
#    command: uwsgi --ini /djangocode/uwsgi.ini
    volumes:
      - .:/djangocode
    ports:
      - "80:8000"
    expose:
      - "8000"
    links:
      - mysql
    depends_on: # 依赖关系
      - mysql
    environment:
      - DEBUG=False
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: my_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=iflve.com"
      - "MYSQL_DATABASE=iflve_bigdata"
      - "MYSQL_USER=dagedan"
      - "MYSQL_PASSWORD=iflve.comSs123456.."
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
